### ISSUE TITLE
URGENT! on complete, function run multiple times

### ISSUE THREAD

**Issue by BelieveInBunny** [pavanpabs/react-scratchcard-v3#1]
I am having trouble with the function, Function is called multiple time **on complete** so that it send multiple request. It doesn't stop on first request. Even if I add "If", I have tried number of ways to fix it.
But I am unable to resolve it.

**Comment by PavanSomarathne** [comment]
Use the original npm package https://github.com/dopey2/react-scratchcard-v2

**Comment by BelieveInBunny** [comment]
Yes, tried using it as well. Same issue

**Comment by BelieveInBunny** [comment]
found the issue, dev is helping to fix it.
Thank you very much for the reply. Really apprecaite it
